create table USER
(
    ID         BiGINT PRIMARY KEY AUTO_INCREMENT,
    NAME       VARCHAR(10),
    TEL        VARCHAR(20) UNIQUE,
    AVATAR_URL VARCHAR(1024),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
)
