INSERT INTO SHOPPING_CART (SHOP_ID, GOODS_ID, USER_ID, NUMBER, STATUS)
VALUES (1, 1, 1, 8, "ok");

INSERT INTO SHOPPING_CART (SHOP_ID, GOODS_ID, USER_ID, NUMBER, STATUS)
VALUES (1, 2, 1, 5, "ok");

INSERT INTO SHOPPING_CART (SHOP_ID, GOODS_ID, USER_ID, NUMBER, STATUS)
VALUES (2, 3, 1, 1, "ok");

INSERT INTO SHOPPING_CART (SHOP_ID, GOODS_ID, USER_ID, NUMBER, STATUS)
VALUES (3, 5, 1, 1, "ok");

INSERT INTO SHOPPING_CART (SHOP_ID, GOODS_ID, USER_ID, NUMBER, STATUS)
VALUES (3, 4, 3, 2, "ok");

INSERT INTO SHOPPING_CART (SHOP_ID, GOODS_ID, USER_ID, NUMBER, STATUS)
VALUES (4, 6, 3, 1, "ok");

INSERT INTO SHOPPING_CART (SHOP_ID, GOODS_ID, USER_ID, NUMBER, STATUS)
VALUES (1, 2, 2, 1, "ok");

INSERT INTO SHOPPING_CART (SHOP_ID, GOODS_ID, USER_ID, NUMBER, STATUS)
VALUES (2, 3, 2, 1, "ok");

INSERT INTO SHOPPING_CART (SHOP_ID, GOODS_ID, USER_ID, NUMBER, STATUS)
VALUES (3, 5, 2, 1, "ok");

INSERT INTO SHOPPING_CART (SHOP_ID, GOODS_ID, USER_ID, NUMBER, STATUS)
VALUES (4, 6, 2, 1, "ok");





