embedded:
  baseUrl:
    ip: 10.40.95.56
  zookeeper:
    port: 2181
  redis:
    port: 6379

server:
  port: 8081

spring:
  application:
    name: wechat-shop-main
  datasource:
    url: jdbc:mysql://${embedded.baseUrl.ip}:3306/shop
    username: root
    password: my-secret-pw
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  config-location: classpath:db/mybatis/config.xml

shop:
  orderService:
    version: 1.0.0
    url: ""
  redis:
    host: ${embedded.baseUrl.ip}
    port: ${embedded.redis.port}

dubbo:
  registry:
    address: zookeeper://${embedded.baseUrl.ip}:${embedded.zookeeper.port}
