INSERT INTO `ORDER` (USER_ID, TOTAL_PRICE, ADDRESS, EXPRESS_COMPANY, EXPRESS_ID, STATUS, CREATED_AT, UPDATED_AT)
VALUES (1, 1000, 'address', '顺丰', '1', 'ok', NOW(), NOW());
INSERT INTO `ORDER` (USER_ID, TOTAL_PRICE, ADDRESS, EXPRESS_COMPANY, EXPRESS_ID, STATUS, CREATED_AT, UPDATED_AT)
VALUES (1, 2000, 'address', '顺丰', '1', 'ok', NOW(), NOW());
INSERT INTO `ORDER` (USER_ID, TOTAL_PRICE, ADDRESS, EXPRESS_COMPANY, EXPRESS_ID, STATUS, CREATED_AT, UPDATED_AT)
VALUES (2, 1000, 'address', '邮政', '2', 'ok', NOW(), NOW());
INSERT INTO `ORDER` (USER_ID, TOTAL_PRICE, ADDRESS, EXPRESS_COMPANY, EXPRESS_ID, STATUS, CREATED_AT, UPDATED_AT)
VALUES (3, 3000, 'address', '邮政', '2', 'ok', NOW(), NOW());
INSERT INTO `ORDER` (USER_ID, TOTAL_PRICE, ADDRESS, EXPRESS_COMPANY, EXPRESS_ID, STATUS, CREATED_AT, UPDATED_AT)
VALUES (3, 3500, 'address', '邮政', '2', 'ok', NOW(), NOW());

INSERT INTO ORDER_GOODS (GOODS_ID, ORDER_ID, NUMBER)
VALUES (1, 1, 10);
INSERT INTO ORDER_GOODS (GOODS_ID, ORDER_ID, NUMBER)
VALUES (3, 1, 2);
INSERT INTO ORDER_GOODS (GOODS_ID, ORDER_ID, NUMBER)
VALUES (5, 2, 4);
INSERT INTO ORDER_GOODS (GOODS_ID, ORDER_ID, NUMBER)
VALUES (2, 3, 1);
INSERT INTO ORDER_GOODS (GOODS_ID, ORDER_ID, NUMBER)
VALUES (3, 3, 2);
INSERT INTO ORDER_GOODS (GOODS_ID, ORDER_ID, NUMBER)
VALUES (4, 4, 4);
INSERT INTO ORDER_GOODS (GOODS_ID, ORDER_ID, NUMBER)
VALUES (3, 5, 1);
INSERT INTO ORDER_GOODS (GOODS_ID, ORDER_ID, NUMBER)
VALUES (6, 5, 2);
INSERT INTO ORDER_GOODS (GOODS_ID, ORDER_ID, NUMBER)
VALUES (5, 5, 5);
