embedded:
  baseUrl:
    ip: 10.40.95.56
  zookeeper:
    port: 2181

server:
  port: 8080

spring:
  application:
    name: wechat-shop-order
  datasource:
    url: jdbc:mysql://${embedded.baseUrl.ip}:3306/order
    username: root
    password: my-secret-pw
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  config-location: classpath:db/mybatis/config.xml

shop:
  orderService:
    version: 1.0.0

dubbo:
  scan:
    base-packages: com.bowen.shop.order.service

  protocol:
    name: dubbo
    ## Random port
    port: -1
  registry:
    address: zookeeper://${embedded.baseUrl.ip}:${embedded.zookeeper.port}

